config/routes.rb
Blocipedia::Application.routes.draw do
  get "charges/create"
  get "users/owned_wikis"
  get "users/collaborated_wikis"
  resources :wikis

  resources :charges, only: [:new, :create]

  get "welcome/index"
  get "welcome/about"

  devise_for :users

  root to: 'welcome#about'
  end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #:confirmable
  has_many :wikis
  has_many :collaborations
  #has_many :wikis_i_am_collaborating_on, through: :collaborations, class_name: 'Wiki'
  has_many :wikis_i_am_collaborating_on, :through => :collaborations, :source => :wiki

  def role?(base_role)
    role == base_role.to_s
  end

  def self.all_except(user)
    where.not(id: user)
  end
  #protected
  #def confirmation_required?
  #  false
  #end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  #has_many :collaborators, through: :collaborations, source: :user
  has_many :collaborators, :through => :collaborations, :source => :user
  #has_many :collaborators, through: :collaborations, class_name: 'User'


  #scope :visible_to, -> (user) { user ? all : where(premium: true) }
  #scope :visible_to, -> (wiki) { user ? all : where(private: true) }

  # a different try at scopes
  #scope :visible_to, -> (user) { user ? all : where(public: true) }

  def public?
    !private
  end


  #scope :private_wikis, -> { where private: true }
  #scope :public_wikis, -> { where private: false }

  def markdown_body
    renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    renderer.render body
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_action :authenticate_user!

  def new
    @stripe_btn_data = {
        key: "#{ Rails.configuration.stripe[:publishable_key] }",
        description: "BigMoney Membership - #{current_user.email}",
        amount: 1_000
        # We're like the Snapchat for Wikipedia. But really.
    }
  end

  def create
    @amount = 10_00

    # Creates a Stripe Customer object, for associating
    # with the charge

    #logger.info “Started Charges create”

    customer = Stripe::Customer.create(
        email: current_user.email,
        card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
        customer: customer.id, # Note -- this is NOT the user_id in your app
        amount: @amount,
        description: "BigMoney Membership - #{current_user.email}",
        currency: 'usd'
    )

    #logger.info “Got response from Stripe charge inspect”

    current_user.update_attribute(:premium, true)

    flash[:success] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to wikis_path(current_user)

      # Stripe will send back CardErrors, with friendly messages
      # when something goes wrong.
      # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to edit_wiki_path

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :load_user

  def load_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user == @user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_action :authenticate_user!

  def index
    @wikis = current_user.wikis
    @wikis_i_am_collaborating_on = current_user.wikis_i_am_collaborating_on
  end

  def new
    @wiki = Wiki.new
    @users = User.all_except(current_user)
  end

  def create
    @wiki = current_user.wikis.build(wiki_params)

    if @wiki.save
      flash[:success] = "Your Wiki has been created!"
      redirect_to @wiki
    else
      flash[:error] = "Your Wiki creation failed. Please try again."
      redirect_to new_wiki_path
    end
  end

  def show
    @wiki = current_user.wikis.find(params[:id])

  end

  def update
    @wiki = current_user.wikis.find(params[:id])
    @users = User.all
    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @wiki = current_user.wikis.find(params[:id])
    @wikis_i_am_collaborating_on = current_user.collaborations
    @users = User.all_except(current_user)
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :collaborator_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.haml
%h1 Your Charges
%p Thanks you just paid!

app/views/charges/new.html.haml
%h2 Upgrade Your Account

= form_tag charges_path do
  = hidden_field_tag :amount, @stripe_btn_data[:amount]

  %h4 Charge me $10 for a paid account
  %script{ class: 'stripe-button', src: "https://checkout.stripe.com/checkout.js", data: @stripe_btn_data }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <!--add url for google font merriweather here get from google.com/fonts (maybe) -->
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container" id="primary-menu">
  <ul class="nav nav-tabs">
    <!--need to create class for current page then add to each li-->
    <!--<li><%= link_to "Home", welcome_index_path,:class => current_page?(welcome_index_path) ? 'current':'' %></li>-->
    <li><%= link_to "About", welcome_about_path %></li>

    <div class="pull-right user-info">
      <% if current_user %>
          Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>

  </ul>
</div>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/about.html.haml
%p
.jumbotron.shadow
	%h1 Hello, wikis!
	%p This is a Wikipedia-type app to play with Ruby on Rails and some tools that go with it.
	%p
		- if current_user
			= link_to "Keep Going", wikis_path, class: 'btn button-primary btn-lg'
		- else
			= link_to "Try It", new_user_session_path, class: 'btn button-primary btn-lg'

%h1 About This Application

%h3
	%p Features include wikis that have collaboration, privacy, and paid settings.

%h3
	%p Some tools used include:
%li Haml, JQuery, Sass, and Coffee for presentation;
%li Rspec, Capybara, and Factory Girl for testing;
%li Stripe for payments;
%li Sqlite (dev) and PostgreSql (production) for database management.
%li Has_many :through association.
%br

%h3
	Demo user:
%h4
	%strong email:
	member@example.com
%h4
	%strong password:
	welcome1234
%p
%p This was built by Michelle Bonat awhile ago, but I keep it around to remember those days.

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml

app/views/wikis/_form.html.haml
/%h3 Edit Your Wiki
.col-md-4
  .panel.panel-primary
    .panel.new-panel-heading
      %h3.new-panel-title Update It Here
    .panel-body
      %p It's simple! Just complete this form.
      =form_for @wiki do |f|
        .form-group
          .input-group
            .input-group-addon
              %span.glyphicon.glyphicon-arrow-right
            = f.text_field :title, :class => 'form-control', :placeholder => "Title"
            = f.text_field :body, :class => 'form-control', :placeholder => "Body"

        - if current_user.premium
          %h2 Add a Collaborator
          %ul
            - @users.each do |user|
              %li
                = check_box_tag "wiki[collaborator_ids][]", user.id, @wiki.collaborators.include?(user)
                = user.name
        - if current_user.premium
          %p
            %label.checkbox{ :for => "private" }
            = f.label :private?
            = f.check_box :private, :class => "checkbox"
        = f.submit 'Update', class:'btn button-primary'

      /    = flash[:notice] = "Your update was saved."

app/views/wikis/edit.html.haml
%h3 Update Wiki
= render 'form'

app/views/wikis/index.html.haml
%h1 <strong>Your Pages</strong>

%h2 Pages You Own

%ul
  - @wikis.each do |wiki|
    %li= link_to wiki.title, wiki

%h2 Pages On Which You Have Collaborated

%ul
  - @wikis_i_am_collaborating_on.each do |wiki|
    %li= link_to wiki.title, wiki

= link_to "Create New Wiki", new_wiki_path, :class => 'button-secondary'

app/views/wikis/new.html.haml
%h3 New Wiki
.col-md-4
	.panel.new-panel-primary
		.panel.new-panel-heading
			%h3.panel-title Create A Wiki
		.panel-body
			%p It's simple! Just complete this form. Clicking the checkbox makes it a private wiki.
			=form_for @wiki do |f|
				.form-group
					.input-group
						.input-group-addon
							%span.glyphicon.glyphicon-arrow-right
						= f.text_field :title, :class => 'form-control', :placeholder => "Title"
						= f.text_field :body, :class => 'form-control', :placeholder => "Body"
				%p
					%label.checkbox{ :for => "private" }
					= f.label :private?
					= f.check_box :private, :class => "checkbox" "center"
					%p
					= f.submit 'Generate Wiki', class:'btn button-primary'

.col-md-4
	%section
		= link_to "See Your Wikis", wikis_path, :class => 'button-secondary'

app/views/wikis/show.html.haml
%h1= @wiki.title
%p= raw @wiki.markdown_body

= link_to "Update This Wiki", edit_wiki_path, :class => 'button-secondary'

= link_to "Create New Wiki", new_wiki_path, :class => 'button-secondary'

= link_to "See Your Wikis", wikis_path, :class => 'button-secondary'